language: en

pipeline:
# Using a recommended pipeline for general purpose bots.
# It includes components for robust NLU.
- name: WhitespaceTokenizer
- name: RegexFeaturizer # Good for things like IDs, emails
- name: LexicalSyntacticFeaturizer # Looks at word order and parts of speech
- name: CountVectorsFeaturizer # Bag-of-words for intents
- name: CountVectorsFeaturizer
  analyzer: char_wb # Character n-grams for typos and morphology
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100 # Adjust based on your dataset size and performance
  constrain_similarities: true
- name: EntitySynonymMapper # If you define synonyms for entities
- name: ResponseSelector # For simple chit-chat or FAQ-like responses
  epochs: 100
- name: FallbackClassifier
  threshold: 0.4 # If intent confidence is below this, trigger fallback
  ambiguity_threshold: 0.1 # If top two intents are too close

policies:
- name: MemoizationPolicy # Remembers past conversations
- name: RulePolicy # For handling specific rules, like form activation, chitchat
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback" # You might want to create a custom fallback action
  enable_fallback_prediction: true
- name: TEDPolicy # Transformer Embedding Dialogue policy for generalization
  max_history: 7 # How many dialogue turns to consider
  epochs: 100 # Adjust based on your data
  constrain_similarities: true
- name: FormPolicy # Essential for handling forms